Refactor example konuma
yuji91/RefactoringRuby_Example_01 pull request #2
Opened 2020-05-28 12:41 UTC by konumashuri

2020-05-28 13:03 UTC, yuji91 requested changes
補足をお願いしたい点について、コメントさせていただきました🙇‍♂️

2020-05-28 13:03 UTC, yuji91 commented on 8_16_initialize_attribute.rb
> +    @_average_score ||= scores.average.to_i
すみません、自分が知らなかったので`@_average_score`とアンダースコアを付与する意味について補足をお願いしたいです！少し調べたのですがうまく探せませんでした😭

また、下記のように記載しなくても、問い合わせメソッド実行時にDBへのアクセス処理を実行しないで済む形になるかどうか確認したいです🙏
`@_average_score ||= User.pluck(:score).average.to_i`

2020-05-28 13:03 UTC, yuji91 commented on 9_6_nested_condition.rb
> +  COUPON_PRICE = 10_000
小沼さん数字をアンダースコアで区切る派なんですね！
この点RUNTEQのRubocopでも有効にするか迷いました。。

自分が少し適当に作っているのですが、定数を宣言する際は本来は`freeze`するべきでしょうか？

2020-05-28 13:03 UTC, yuji91 commented on 8_16_initialize_attribute.rb
> +    @_media_score ||= scores.median.to_i
このコードだと無理やりArrayClassに`median`と`average`メソッドを`spec_helper.rb`で定義して使っているのですが、本来だとどのように記載すべきかについてもアドバイス頂けるとありがたいです🙏
（libフォルダ以下にrubyファイルを記載するのか、外部の何かしらのlibraryを使うのかが気になっています。）
元々は中央値を判定するメソッドを探していて下記の例を見つけて gem facetsを導入していたのですがうまく使えなかったので今の形になっています😥
https://www.rubydoc.info/github/rubyworks/facets/Array:median

今調べたら別のgemもあるようでした。
https://github.com/ankane/active_median

2020-05-28 13:15 UTC, konumashuri commented on 8_16_initialize_attribute.rb
> +    @_average_score ||= scores.average.to_i
## 意味について
これは、実務で他の人がやってて良いなと思った書き方ですね！なので特定のスタイルガイドのようなソースはないです。

アンダースコアを入れる意味は下記2つだと思っています！
- キャッシュ用のインスタンス変数として使っていること
- 他と競合しないようにすること

## ソース
一応、この辺りの記事見る限り採用してる人はいるっぽい。
http://adarsh.io/use-an-underscore-when-memoizing-in-ruby/

https://www.google.com/search?q=ruby+add+underscore+to+cache+instance+variables&oq=ruby+add+underscore+to+cache+instance+variables&aqs=chrome..69i57j69i64.12678j0j1&sourceid=chrome&ie=UTF-8

## 他の書き方
いや、他の書き方だと難しいねー。
ユーザーは振り分けられる対象っていうのもあるから、averageとmedianのスコアを持つ計算用のクラスを一つ作るとかは良いかも

```
class User::Classification
  def initialize(users)
    self.users = users
    self.average_score = User.pluck(:score).average.to_i
    self.median_xxxxxx
  end
end
```

みたいな形で！
場合によるけど、自動詞になるようにクラスを分けると個人的にはスッキリするイメージ。

2020-05-28 13:19 UTC, konumashuri commented on 9_6_nested_condition.rb
> +  COUPON_PRICE = 10_000
## アンダースコア
そうだねー、今の仕事で0.000_000_1とか、逆に1_000_000とかの桁を使うことが多くてその名残かも。
あとはエンジニアの人って1,000,000で百万とかすぐに読める人少ないからその練習のためにもつけるのはありかなと

## freeze
定数宣言のfreezeあんまり意味ない気がしてなしで良いと思うｗ
freezeで宣言したあとも普通に再代入できるし jsのconstant的な使い方できないから

ruby 3で必須になるけど、それはrubyへのPRでfreezeつけたやつが多すぎるからという話だし。

2020-05-28 13:22 UTC, konumashuri commented on 8_16_initialize_attribute.rb
> +    @_media_score ||= scores.median.to_i
rails, rubyに元からあるクラスを拡張する場合は `config/initializes` 配下に書くようにしてる！今回でいうと `config/initializers/core_ext/array.rb` 的な感じですね！

`core_ext` は他の `String` とかを拡張したくなったときとかにファイルが散らからないように追加してる。

libでも良いけどライブラリというよりは、コア機能の拡張だからinitializersで起動時に定義される方が気持ち悪くないかなという感覚ですね笑

initializers以外に書き始めるとそれこそ、`lib`なのか `app`なのかいろいろな場所で書かれそうで怖いというのもある！

2020-05-28 14:45 UTC, yuji91 commented on 8_16_initialize_attribute.rb
> +    @_average_score ||= scores.average.to_i
@konumashuri 
追加で1点確認したいです！

33行目で`scores = User.pluck(:score)`と記載して
34行目に`@_average_score ||= scores.average.to_i`と書いているのは、
処理の重い`avarage`は毎回の実行を避け、処理の早い`pluck`は33行目でメソッド実行時に毎回実行する形でも問題ないということでしょうか？🤔

また`@_average_score ||= User.pluck(:score).average.to_i`と1行で記載せずに分けている点について意図があれば教えていただきたいです🙇‍♂️

2020-05-28 14:47 UTC, yuji91 commented on 9_6_nested_condition.rb
> +  COUPON_PRICE = 10_000
> 1,000,000で百万とかすぐに読める人少ない

確かに英語圏でないとあまり馴染みないですね！

> freezeで宣言したあとも普通に再代入できる

知らなかったです、、ありがとうございます🙏

2020-05-28 14:48 UTC, yuji91 commented on 8_16_initialize_attribute.rb
> +    @_media_score ||= scores.median.to_i
> libでも良いけどライブラリというよりは、コア機能の拡張だからinitializersで起動時に定義される方が気持ち悪くないかな

納得しました！！

2020-05-28 14:50 UTC, yuji91 requested changes
よろしければこちら1点だけ確認したいです！
https://github.com/yuji91/RefactoringRuby_Example_01/pull/2#discussion_r431894386

2020-05-29 14:49 UTC, shurijoc commented on 8_16_initialize_attribute.rb
> +    @_average_score ||= scores.average.to_i
あ、これミスだ！ `@_average_score ||= User.average(:score)` で良いと思う！
pluckを使うかaverageを使うかについては基本的にはmysqlの方が早いからaverageを使うで良いと思う。

2020-05-30 01:19 UTC, yuji91 commented on 8_16_initialize_attribute.rb
> +    @_average_score ||= scores.average.to_i
> @_average_score ||= User.average(:score) で良いと思う！

承知しました！ありがとうございます🙇‍♂️

> pluckを使うかaverageを使うかについては基本的にはmysqlの方が早いからaverageを使うで良いと思う。

なるほどです！
`average`がActiveRecordに実装されていることを知らずに、課題のためにArrayクラスにメソッド定義しちゃってました😅

2020-05-30 01:21 UTC, yuji91 approved these changes
@konumashuri 
解説ありがとうございました！🙏

マージすると課題が直ってしまうので、PRはこのまま残しておきたいと思います！

2024-07-23 23:46 UTC, closed without merging